### ISSUE TITLE
Handle GitHub rate limit errors

### ISSUE THREAD

**Issue by omerlh** [snyk-labs/snyk-scm-refresh#41]
Example of error:

```
Traceback (most recent call last):
  File "/home/circleci/project/snyk-scm-refresh/app/gh_repo.py", line 11, in get_repo_manifests
    gh_repo = common.gh_client.get_repo(snyk_repo_name)
  File "/home/circleci/.pyenv/versions/3.9.1/lib/python3.9/site-packages/github/MainClass.py", line 312, in get_repo
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/circleci/.pyenv/versions/3.9.1/lib/python3.9/site-packages/github/Requester.py", line 317, in requestJsonAndCheck
    return self.__check(
  File "/home/circleci/.pyenv/versions/3.9.1/lib/python3.9/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for user ID 18642669.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/circleci/project/snyk-scm-refresh/snyk_scm_refresh.py", line 51, in <module>
    run()
  File "/home/circleci/project/snyk-scm-refresh/app/app.py", line 95, in run
    projects_import = snyk_repo.add_new_manifests(common.ARGS.dry_run)
  File "/home/circleci/project/snyk-scm-refresh/app/snyk_repo.py", line 39, in add_new_manifests
    gh_repo_manifests = get_repo_manifests(self.full_name, self.origin)
  File "/home/circleci/project/snyk-scm-refresh/app/gh_repo.py", line 17, in get_repo_manifests
    gh_repo = common.gh_enterprise_client.get_user().get_repo(snyk_repo_name)
AttributeError: module 'common' has no attribute 'gh_enterprise_client'
```

**Comment by johnjelinek** [comment]
bummer, I got this too
